# Generated by Django 5.0.1 on 2024-02-02 21:07

import common.helper
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponseData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.helper.make_uuid,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quran_res", models.TextField(blank=True, null=True)),
                ("hadeeth_res", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserPrompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=common.helper.make_uuid,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("prompt", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "response",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="magicai.responsedata",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
